image: python:3.11

stages:
  - deploy

deploy:
  stage: deploy
  only:
    refs:
      - main
  script:
    - apt update && apt install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - ssh -o StrictHostKeyChecking=no -i id_rsa $VCM_USER@$VCM_IP "bash -l -c 'export PATH=\$PATH:/usr/bin && cd /home/vcm/APP_WHALESCALE && git checkout main && git pull origin main && docker compose down && docker compose build && docker compose up -d'"
