# This file defines the process taken by GitLab after a merge to a protected branch
# Author: Jason Fitzpatrick

image: docker:24.0.5

stages:
  - deploy

before_script:
  - apk add --no-cache openssh-client

deploy-prod:
  stage: deploy
  only:
    refs:
      - main
  variables:
    ENVIRONMENT: prod
  script:
    - echo "$SSH_PRIVATE_KEY" > gitlab_vcm
    - chmod 600 gitlab_vcm
    - |
      ssh -o StrictHostKeyChecking=no -i gitlab_vcm $VCM_USER_PROD@$VCM_IP_PROD "
      cd /home/vcm/APP_WHALESCALE/app_WhaleScale && 
      git fetch &&
      git checkout main && 
      git pull origin main && 
      export POSTGRES_DB='$POSTGRES_DB' &&
      export POSTGRES_USER='$POSTGRES_USER' &&
      export POSTGRES_PASSWORD='$POSTGRES_PASSWORD' &&
      export DJANGO_SECRET_KEY='$DJANGO_SECRET_KEY' &&
      export DJANGO_SUPERUSER_PASSWORD='$DJANGO_SUPERUSER_PASSWORD' &&
      export POSTGRES_HOST='$POSTGRES_HOST' &&
      export ENVIRONMENT='$ENVIRONMENT' &&
      export DEV_ALLOWED_HOSTS='$DEV_ALLOWED_HOSTS' &&
      export DEV_DEBUG='$DEV_DEBUG' &&
      export PROD_ALLOWED_HOSTS='$PROD_ALLOWED_HOSTS' &&
      export PROD_DEBUG='$PROD_DEBUG' &&
      docker-compose -f docker-compose.prod.yml down -v && 
      docker-compose -f docker-compose.prod.yml up -d --build &&
      sleep 15 &&
      docker-compose -f docker-compose.prod.yml exec -T backend python manage.py makemigrations &&
      docker-compose -f docker-compose.prod.yml exec -T backend python manage.py migrate
      "

deploy-dev:
  stage: deploy
  only:
    refs:
      - dev
  variables:
    ENVIRONMENT: dev
  script:
    - echo "$SSH_PRIVATE_KEY" > gitlab_vcm
    - chmod 600 gitlab_vcm
    - |
      ssh -o StrictHostKeyChecking=no -i gitlab_vcm $VCM_USER_DEV@$VCM_IP_DEV "
      cd /home/vcm/APP_WHALESCALE && 
      git fetch &&
      git checkout dev && 
      git pull origin dev && 
      export POSTGRES_DB='$POSTGRES_DB' &&
      export POSTGRES_USER='$POSTGRES_USER' &&
      export POSTGRES_PASSWORD='$POSTGRES_PASSWORD' &&
      export DJANGO_SECRET_KEY='$DJANGO_SECRET_KEY' &&
      export DJANGO_SUPERUSER_PASSWORD='$DJANGO_SUPERUSER_PASSWORD' &&
      export POSTGRES_HOST='$POSTGRES_HOST' &&
      export ENVIRONMENT='$ENVIRONMENT' &&
      export DEV_ALLOWED_HOSTS='$DEV_ALLOWED_HOSTS' &&
      export DEV_DEBUG='$DEV_DEBUG' &&
      export PROD_ALLOWED_HOSTS='$PROD_ALLOWED_HOSTS' &&
      export PROD_DEBUG='$PROD_DEBUG' &&
      docker-compose -f docker-compose.dev.yml down -v && 
      docker-compose -f docker-compose.dev.yml up -d --build
      "
