version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  backend:
    build:
      context: ./whale_scale
      dockerfile: Dockerfile.dev
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ENVIRONMENT: ${ENVIRONMENT}
      PROD_ALLOWED_HOSTS: ${PROD_ALLOWED_HOSTS}
      DEV_ALLOWED_HOSTS: ${DEV_ALLOWED_HOSTS}
      PROD_DEBUG: ${PROD_DEBUG}
      DEV_DEBUG: ${DEV_DEBUG}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    build:
      context: ./whale_scale/frontend
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_API_URL=https://dev-whale-scale.colab.duke.edu
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
