version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: whale_scale
      POSTGRES_USER: whale_admin
      POSTGRES_PASSWORD: js2zyBull88
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=https://whale-scale.colab.duke.edu
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
