server {
    listen 80;
    server_name dev-whale-scale.colab.duke.edu;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name dev-whale-scale.colab.duke.edu;

    ssl_certificate /etc/letsencrypt/live/dev-whale-scale.colab.duke.edu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev-whale-scale.colab.duke.edu/privkey.pem;

    # 🚨 Add this line here to fix uploading large image:
    client_max_body_size 100M;

    root /app/build;

    location / {
        try_files $uri $uri/ /index.html;
        index index.html;
        expires -1;
        add_header Cache-Control "no-store, must-revalidate";
    }

    location /static/ {
        alias /app/build/static/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
