# Generated by Django 5.1.5 on 2025-04-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("measurement_type", models.CharField(max_length=50)),
                ("user_image_path", models.TextField()),
                ("image_timestamp", models.DateTimeField()),
                ("measurement_timestamp", models.DateTimeField()),
                ("coordinate_data", models.JSONField()),
                ("pixel_dimension", models.FloatField(blank=True, null=True)),
                ("pixel_count", models.IntegerField(blank=True, null=True)),
                ("scaled_dimension", models.FloatField(blank=True, null=True)),
                ("focal_length", models.FloatField(blank=True, null=True)),
                ("sensor_width", models.FloatField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("field_of_view", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("altitude_offset", models.FloatField(blank=True, null=True)),
                ("gps_latitude", models.FloatField(blank=True, null=True)),
                ("gps_longitude", models.FloatField(blank=True, null=True)),
                (
                    "camera_make",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "camera_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
