# Generated by Django 5.1.5 on 2025-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
