# Generated by Django 5.1.5 on 2025-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="measurement_name",
            new_name="subject_group",
        ),
        migrations.AddField(
            model_name="measurement",
            name="actual_measurement",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="subject_age",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="subject_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
